"""What a removal pull request says: its title, body and commit message.

Extracted from ``orchestrate`` so ``pr_command`` produces byte-identical
content when it regenerates a pull request. A second implementation would
drift — and the first thing to drift would be the caveats, which are the part
a reviewer most needs to be able to trust.

Nothing here touches the network, the filesystem or git: given a candidate and
a config it returns strings.
"""

from __future__ import annotations

import logging
import re
from pathlib import PurePosixPath
from urllib.parse import quote

from flag_cleanup.client import Candidate
from flag_cleanup.config import Config
from flag_cleanup.urls import without_userinfo

logger = logging.getLogger(__name__)

#: Directory names a build usually writes into. Used in exactly two places,
#: both chosen so that being WRONG about one is cheap:
#:
#: 1. Skipped when scanning for references the transform could not process.
#:    That scan's answer is rendered in the PR body as "N file(s) still
#:    reference this flag and were not processed", so its cost is a wrong,
#:    scary caveat on a complete removal. A repository that commits its
#:    compiled output (a published library: ``dist/index.js``,
#:    ``dist/index.mjs``) got that caveat on every PR, naming build artefacts
#:    the reviewer cannot act on and that the next build regenerates anyway.
#: 2. :func:`_rewritten_build_output`, which annotates the PR body with the
#:    generated files this run DID rewrite.
#:
#: NOT applied to the transform, and #2634 is the record of why that stayed
#: true once the js language made these directories reachable. These names are
#: conventions, not guarantees: a repository that keeps hand-written source in
#: one of them must still be cleaned correctly, and a `.ts` file here is
#: processed exactly as before. The asymmetry is the whole design — the worst
#: case of a wrong skip is a missing warning, or a mislabelled note, about a
#: generated file; the worst case of a wrong TRANSFORM skip is a flag left
#: half-removed, in a pull request claiming it was removed.
#:
#: That asymmetry USED TO BE UNREACHABLE on this side, and the history is worth
#: keeping: ``_unprocessed_references`` scanned only the extensions no
#: configured language covered, so with `js` configured a `.js` file was never
#: examined and this constant was dead code for it — #2634's "move both halves
#: or neither" could not be honoured by editing this set, because emptying it
#: entirely still yielded no caveat. The scan now covers every known extension,
#: so the skip below is live again and is the only thing keeping committed build
#: output out of the caveat. Pinned by
#: ``test_emptying_the_generated_dirs_skip_now_restores_the_caveat``.
_GENERATED_DIRS = frozenset(
    {"dist", "build", "out", "coverage", ".next", ".nuxt", ".output", ".svelte-kit", ".turbo"}
)


def is_dead(status: str) -> bool:
    """Is this candidate ``Dead`` (ready PR) rather than ``Stale`` (draft)?

    ``status`` arrives PascalCase on the wire (``"Dead"``/``"Stale"``), so the
    comparison is case-insensitive — a literal ``== "dead"`` would quietly
    make EVERY pull request a draft. Anything unrecognized is treated as the
    safer draft case, matching what ``_warn_on_unrecognized_status`` promises.
    """
    return status.strip().lower() == "dead"


def pr_title(candidate: Candidate) -> str:
    # A PR title is plain text, not markdown — no code fences here.
    word = "dead" if is_dead(candidate.status) else "stale"
    return f"Remove {word} feature flag: {_one_line(candidate.key)}"


def commit_message(candidate: Candidate) -> str:
    served = "true" if candidate.treatment else "false"
    return (
        f"chore: remove feature flag {_one_line(candidate.key)}\n"
        "\n"
        f"Status: {_one_line(candidate.status)}. The flag serves {served}, so the "
        f"code behind the {'on' if candidate.treatment else 'off'} branch was kept.\n"
        "\n"
        "Generated by the Featureflip flag-cleanup Action (deterministic Piranha "
        "rewrite, no LLM).\n"
    )


def _and_list(items: list[str]) -> str:
    """Join for prose: ``a``; ``a and b``; ``a, b and c``."""
    if len(items) <= 1:
        return "".join(items)
    return f"{', '.join(items[:-1])} and {items[-1]}"


def _rewritten_build_output(diff: str) -> tuple[str, ...]:
    """Paths in ``diff`` that sit under a conventionally-generated directory.

    Since #2607 the js language covers `.js`/`.mjs`/`.jsx`/`.cjs`, so a
    repository that commits its bundles has them REWRITTEN rather than merely
    reported (#2634). That is the correct behaviour and this tool keeps it: a
    generated-dir file is transformed like any other, so no live read can
    survive one and the "flag removed" claim stays true. Measured, the rewrite
    lands even on minified output — bundlers mangle local names but preserve
    property access and string literals, so `t.client.boolVariation("k",!1)`
    matches the rules exactly as the source it came from does.

    What it costs is review: a minified hunk is unreviewable in practice, and a
    reviewer who finds one in a PR titled "Remove dead feature flag" has no way
    to tell why it is there. So the body names them, the way ``stranded``
    names the statements it deleted — the fix for #2634 is information, not a
    behaviour change.

    Reading the DIFF rather than the candidate list is deliberate: the diff is
    the authoritative record of what this pull request actually contains, so
    the note cannot name a file the PR does not touch. And it is the safe place
    to be approximate — a header-shaped content line mislabels a note, which a
    reviewer can ignore, where the same slip in a transform-side prune would
    half-remove a flag. Every edge case named below is pinned by
    ``test_rewritten_build_output_reads_only_real_diff_headers``, including
    that spoof, which is asserted to produce the stray name rather than
    pretended not to exist.
    """
    paths: list[str] = []
    lines = diff.splitlines()
    for index, line in enumerate(lines[:-1]):
        if not line.startswith("--- a/") or not lines[index + 1].startswith("+++ b/"):
            continue
        before, after = line[len("--- a/") :], lines[index + 1][len("+++ b/") :]
        # `_summaries_to_diff` never renames, so the two halves of a real
        # header always agree. A content line that merely LOOKS like one
        # (`++ b/x` added renders as `+++ b/x`) is unlikely to be preceded by
        # a matching `--- a/x`, and costs only a stray name if it is.
        if before != after:
            continue
        # `parts[:-1]` — directory components only, so a FILE named `dist`
        # is not mistaken for the directory.
        if not _GENERATED_DIRS.isdisjoint(PurePosixPath(before).parts[:-1]):
            paths.append(before)
    return tuple(dict.fromkeys(paths))


def pr_body(
    candidate: Candidate,
    config: Config,
    unprocessed: tuple[str, ...] = (),
    stranded: tuple[tuple[str, str], ...] = (),
    bindings: tuple[tuple[str, str, str], ...] = (),
    generated: tuple[str, ...] = (),
    entries: tuple[tuple[str, str], ...] = (),
    declined: tuple[tuple[str, str], ...] = (),
) -> str:
    """The PR description: what was removed, why, and which branch survived.

    States ``treatment`` in plain English so a reviewer can sanity-check the
    deletion without reading the Piranha rules — the single most likely way
    for this tool to be wrong is keeping the branch the flag was NOT serving.

    ``unprocessed`` (files that still mention the key after the rewrite) is
    called out prominently when non-empty: merging a PR titled "remove flag X"
    while the repo still declares or reads X is the failure mode this tool most
    needs to avoid causing silently.

    ``generated`` is the opposite case and must not be confused with it: those
    files WERE rewritten and the removal really is complete. They are named
    only because a reviewer cannot be expected to make sense of a minified
    hunk. See :func:`_rewritten_build_output`.

    ``bindings`` is a THIRD case, distinct from both: an import or local
    variable the fold left with no remaining use, named for the same reason
    ``stranded`` is — sound by construction, but the code was the customer's.
    It is a separate field, and gets a separate sentence, because
    ``stranded``'s sentence is specifically about statements the language's own
    toolchain proves unreachable, and printing that for an import would be
    false. See :func:`~flag_cleanup.unused.remove_stranded_bindings`.

    ``entries`` is a FOURTH case: a flag-keyed entry — a registry line, an
    override property, an object-type member — deleted under one of the two
    evidence prongs the `*_entries.toml` rules carry (a sibling key that is
    another flag of this project, or a boolean value). Not a read, and named
    for the same reason
    ``bindings`` is: the code was the customer's, and the evidence rule that
    justified deleting it is the thing a reviewer needs to see.

    ``declined`` is the FIFTH, and the only one that is about something this
    tool did NOT do. Those entries set the flag to the branch this removal
    deletes, so both entry prongs left them alone (#3050) and they surface in
    ``unprocessed`` as residual references — where the generic caveat can only
    guess at what they are. This field is what lets the body say which of those
    files the tool understood and why it stopped, so a reviewer reads one
    paragraph instead of bisecting a red build.
    """
    served = "true" if candidate.treatment else "false"
    kept, deleted = ("on", "off") if candidate.treatment else ("off", "on")
    flag_url = (
        f"{_without_userinfo(config.api_url)}/api/v1/orgs/{quote(config.org, safe='')}"
        f"/projects/{quote(config.project, safe='')}"
        f"/flags/{quote(candidate.key, safe='')}"
    )
    lines = [
        f"Removes the {_md_code(candidate.key)} feature flag from this repository.",
        "",
        "| | |",
        "| --- | --- |",
        f"| **Flag** | {_md_cell(_md_code(candidate.key))} |",
        f"| **Status** | {_md_cell(_md_code(candidate.status))} |",
        # Code-spanned like every other server-supplied value: `reason` is API
        # text, and left bare it renders as live markdown in the customer's PR.
        f"| **Reason** | {_md_cell(_md_code(candidate.reason))} |",
        f"| **Treatment** | `{served}` — the flag serves `{served}`, so the "
        f"**{kept}** branch of each check was kept and the **{deleted}** branch "
        "deleted. |",
        # Deliberately NOT a link: this is the API resource (a dashboard deep
        # link cannot be built — that route is keyed by internal ids, and a
        # removal candidate carries only the key), and it needs a bearer token,
        # so auto-linking it would send a reviewer to a 401. In a code span it
        # reads as what it is: the identity of the flag this PR came from.
        f"| **Flag (API resource)** | {_md_cell(_md_code(flag_url))} |",
        "",
    ]
    if not is_dead(candidate.status):
        lines += [
            f"Opened as a **draft** because this flag is {_md_code(candidate.status)}, "
            "not `Dead` — confirm it really is settled, then mark the PR ready.",
            "",
        ]
    if unprocessed:
        shown = unprocessed[:20]
        lines += [
            f"> **⚠️ {len(unprocessed)} file(s) still reference this flag**, so "
            "this PR does **not** remove every mention of it. The reference may "
            "not be a flag read the transform can rewrite (a registry entry, a "
            "test stub, a comment), its extension may be outside the configured "
            f"languages ({_md_cell(', '.join(config.languages))}), or the "
            "engine may not have been able to parse the file — check them by "
            "hand:",
            ">",
            *[f"> - {_md_code(path)}" for path in shown],
            *(
                [f"> - ...and {len(unprocessed) - len(shown)} more"]
                if len(unprocessed) > len(shown)
                else []
            ),
            "",
        ]
    if generated:
        shown = generated[:20]
        # Only the directories actually present — naming all nine reads as
        # boilerplate and tells the reviewer nothing about THIS diff.
        roots = sorted(
            {
                part
                for path in generated
                for part in PurePosixPath(path).parts[:-1]
                if part in _GENERATED_DIRS
            }
        )
        # No `_md_cell`: these are our own literals from `_GENERATED_DIRS`,
        # not API-supplied values, so there is no `|` to escape and escaping
        # would imply otherwise.
        named = _and_list([f"`{root}/`" for root in roots])
        noun = "a directory" if len(roots) == 1 else "directories"
        lines += [
            f"> **ℹ️ This diff includes {len(generated)} build-output file(s).** "
            f"They sit under {named} — {noun} a build normally writes — so if "
            "that is what they are, your next build regenerates them from the "
            "sources this PR just cleaned, and their hunks need no review. "
            "They were rewritten rather than skipped so no read of the flag "
            "survives anywhere in the tree: a minified bundle still reads the "
            "flag, and leaving one alone would make this PR claim more than "
            "it did.",
            ">",
            *[f"> - {_md_code(path)}" for path in shown],
            *(
                [f"> - ...and {len(generated) - len(shown)} more"]
                if len(generated) > len(shown)
                else []
            ),
            "",
        ]
    if stranded:
        # Named rather than left to the diff. The deletion is behaviour-neutral
        # by construction — the language's own toolchain proves these can never
        # run, and the alternative was a branch that cannot go green — but it
        # removes code the customer wrote, and that is not something a reviewer
        # should have to discover.
        #
        # The sentence names every language this can fire for rather than one,
        # because `stranded` is accumulated across the languages of a single
        # run: `_transform_all` extends one list per language, so a PR can
        # carry strands from more than one and there is no single language to
        # name. It said "which Java rejects at compile time" while the repair
        # was Java-only, and kept saying it for the TS family that #2807 added
        # — a false sentence in a customer's pull request.
        lines += [
            f"> **{len(stranded)} statement(s) became unreachable and were "
            "removed.** Folding the flag out left every path above them "
            "returning, which your toolchain rejects rather than warns about: "
            "a compile error in Java (JLS 14.21), a non-zero `dart analyze`, "
            "and a `no-unreachable` error under `eslint:recommended` in "
            "JavaScript and TypeScript. They cannot have run, so nothing "
            "changes behaviour — but they were yours, so here they are:",
            ">",
            *[
                f"> - {_md_code(path)} — {_md_code(statement)}"
                for path, statement in stranded[:20]
            ],
            *(
                [f"> - ...and {len(stranded) - 20} more"]
                if len(stranded) > 20
                else []
            ),
            "",
        ]
    if bindings:
        # A THIRD case alongside `stranded`, sharing its reasoning — sound by
        # construction, but the code was the customer's — without sharing its
        # sentence: that one is specifically about Java statements javac
        # proves unreachable, and an import is not that.
        #
        # The sentences below are deliberately conditional on the counts, and
        # the variable sentence is deliberately PHRASED AS POLICY rather than
        # as an assertion about this run: `Candidate.kind` in `unused.py` is
        # decided before `_apply()` chooses discard-vs-delete, so nothing here
        # knows which one happened to any given variable in this tuple. Saying
        # "were rewritten" when every listed variable was actually an inert
        # deletion would tell the customer something false about their own PR.
        import_count = sum(1 for _, kind, _ in bindings if kind == "import")
        variable_count = len(bindings) - import_count

        def _plural(n: int, noun: str) -> str:
            return f"{n} {noun}" if n == 1 else f"{n} {noun}s"

        counted = []
        if import_count:
            counted.append(_plural(import_count, "import"))
        if variable_count:
            counted.append(_plural(variable_count, "local variable"))

        sentences = [
            # Go is the only unconditionally-true claim here: javac has no
            # built-in lint for either shape and never warns; an unused C#
            # local is a real compiler warning (CS0219) but an unused `using`
            # is an analyzer/IDE concern (IDE0005), not the base compiler; and
            # TypeScript's noUnusedLocals/noUnusedParameters are off by
            # default. So the weaker, defensible claim: a compile error in
            # Go, at most a linter/analyzer/opt-in setting elsewhere.
            "Leaving these in place is a compile error in Go; in Java, C# "
            "and TypeScript it usually is not — at most a linter, "
            "analyzer, or opt-in compiler setting flags it — so in those "
            "three this cleanup is tidiness rather than a fix."
        ]
        if import_count:
            sentences.append(
                "Every import is deleted outright, which cannot change "
                "behaviour."
            )
        if variable_count:
            sentences.append(
                "A variable whose initializer could have a side effect is "
                "rewritten to discard its value rather than deleted, so "
                "nothing stops running; one whose initializer cannot have a "
                "side effect is deleted along with its declaration."
            )

        lines += [
            f"> **{len(bindings)} unused binding(s) were removed.** Folding "
            "the flag out left these with no remaining use — "
            f"{_and_list(counted)}. " + " ".join(sentences),
            ">",
            *[
                f"> - {_md_code(path)} — {kind}: {_md_code(text)}"
                for path, kind, text in bindings[:20]
            ],
            *(
                [f"> - ...and {len(bindings) - 20} more"]
                if len(bindings) > 20
                else []
            ),
            "",
        ]
    if entries:
        count = len(entries)
        noun = "entry was" if count == 1 else "entries were"
        lines += [
            f"> **{count} flag-keyed {noun} removed.** Each was an entry keyed by "
            "this flag inside a literal that is provably about flags: either "
            "another key in the same literal is a different flag of this project, "
            "or the entry's value is a boolean. None is a flag read — these are "
            "the registry and override lines a reviewer used to delete by hand.",
            ">",
            *[f"> - {_md_code(path)} — {_md_code(text)}" for path, text in entries[:20]],
            *([f"> - ...and {count - 20} more"] if count > 20 else []),
            "",
        ]
    if declined:
        count = len(declined)
        noun = "entry was" if count == 1 else "entries were"
        it = "this entry" if count == 1 else "each of these"
        lines += [
            f"> **⚠️ {count} flag-keyed {noun} deliberately left in "
            f"place.** {it.capitalize()} pins the flag to its **{deleted}** "
            "branch — the one this pull request just deleted — so the code "
            "around it may be exercising behaviour that no longer exists. "
            "Stripping the entry would not fix that, it would hide it: a test "
            "whose subject is the removed branch would keep running and start "
            "asserting something the code can no longer do. Delete the entry, "
            "or the code it belongs to, by hand:",
            ">",
            *[
                f"> - {_md_code(path)} — {_md_code(text)}"
                for path, text in declined[:20]
            ],
            *([f"> - ...and {count - 20} more"] if count > 20 else []),
            "",
        ]
    lines += [
        "The rewrite is deterministic (AST transforms), with no LLM involved. "
        "References the tool could not rewrite with confidence were left "
        "untouched, so review the diff before merging.",
        "",
        "_Generated by the Featureflip flag-cleanup Action._",
    ]
    return "\n".join(lines)


def _without_userinfo(url: str) -> str:
    """Strip credentials before this URL is written into a pull-request body.

    Thin alias over :func:`flag_cleanup.urls.without_userinfo`, which is shared
    with the API client — see that module for why one home rather than three.
    """
    return without_userinfo(url)


def _one_line(value: str) -> str:
    return " ".join(value.split())


def _md_code(value: str) -> str:
    """Wrap ``value`` in a code span that its own backticks cannot break out of."""
    text = _one_line(value)
    longest = max((len(run) for run in re.findall(r"`+", text)), default=0)
    fence = "`" * (longest + 1)
    pad = " " if text.startswith("`") or text.endswith("`") else ""
    return f"{fence}{pad}{text}{pad}{fence}"


def _md_cell(value: str) -> str:
    """Escape a value for a markdown table cell.

    Flag keys come from the API, so a stray ``|`` is a plausible way for a PR
    body to come out mangled. GFM honours ``\\|`` inside code spans too.
    """
    return _one_line(value).replace("|", r"\|")


def note_rewritten_build_output(diff: str) -> tuple[str, ...]:
    """Log the build-output files this run rewrote, and return them.

    The PR body carries the same list, but `--dry-run` opens no PR and prints
    the diff instead — so without this the one mode whose entire purpose is
    previewing what a real run would do is the mode that explains a minified
    hunk least. Mirrors :func:`_warn_on_unprocessed_references`, at INFO
    rather than WARNING: nothing here is wrong, the removal is complete, and
    these files regenerate.
    """
    generated = _rewritten_build_output(diff)
    if generated:
        logger.info(
            "%d rewritten file(s) are build output and your next build "
            "regenerates them from the sources just cleaned: %s",
            len(generated),
            ", ".join(generated),
        )
    return generated


def note_removed_entries(entries: tuple[tuple[str, str], ...]) -> None:
    """Log the flag-keyed entries this run deleted; the dry run's only outlet.

    Each entry's text is flattened through :func:`_one_line`, as
    :func:`pr_body` already does for the same values: a deleted entry is
    routinely multi-line (`'k': {\n  default: false,\n},`), and a newline
    inside one item of a `; `-joined list turns a single log record into what
    reads as several unattributed ones in the workflow log.
    """
    if entries:
        logger.info(
            "%d flag-keyed entr%s removed (registry lines, override properties, "
            "type members): %s",
            len(entries),
            "y" if len(entries) == 1 else "ies",
            "; ".join(f"{path}: {_one_line(text)}" for path, text in entries),
        )


def note_declined_entries(declined: tuple[tuple[str, str], ...]) -> None:
    """Log the flag-keyed entries this run DECLINED to delete.

    The mirror of :func:`note_removed_entries`, and needed for a reason that
    one does not have: an entry the rules deleted is in the diff, so the dry
    run would show it even with no log line, while an entry they declined is
    in neither the diff nor the engine's summaries. Without this, a `--dry-run`
    preview of a file the tool deliberately left alone is indistinguishable
    from one it never looked at.

    WARNING rather than INFO, unlike its counterpart. This is the one outcome
    here that asks the reviewer to do something — read the enclosing test and
    decide whether it is still about anything — where a removed entry is a
    thing already done.
    """
    if declined:
        logger.warning(
            "%d flag-keyed entr%s left in place because %s value is the branch "
            "this removal deletes — the enclosing code may be exercising "
            "behaviour that no longer exists, so check %s by hand: %s",
            len(declined),
            "y was" if len(declined) == 1 else "ies were",
            "its" if len(declined) == 1 else "their",
            "it" if len(declined) == 1 else "them",
            "; ".join(f"{path}: {_one_line(text)}" for path, text in declined),
        )
